sudo: required
language: r
warnings_are_errors: false
dist: trusty

# enable RELEASE_CANDIDATE to run (slow & fragile) tests of sampler validity before releases
env:
  global:
    - RELEASE_CANDIDATE=false
    - LINTR_COMMENT_BOT=false
    - secure: cZMk6ONjL+YQ/NjJRujeCsZqnq8+avQ3LunQWp699cMvtWRqF1E6m3kxh9uTHExMduifTreNl7Fn7mPDRSJot5fBi1AMK15yRX4I/W0HSXm5hmdoZAxQCBXEy2Tcd5a6URE9epv0UBFPeWqnI7KHoXwR6BI9R6/kiRbnJJQbS+HItVUXIXfoX57ur5ujlh44JLT6It/p/J5R1nAJDMbjKPifVSxbXF+PMEWrVdJKqaN3IJVXBOYHICf0vQ+sXncF6xsYoYw7B76ZGUHgxF6u+pPCBjMDtmtIiJ9ucE7AnJcQNn4d8ehEimlU5OtEP7uVyJLR2TdDQb/4PIkXKAAT/KrXoDapZYayuBh4ROrPiswlWUp5E+CP5MzOBz4s8V8jlj9qLhJC5Asy8egyQ7BMK0a9Ei4C5vwvumfO+91NhNmsWJPR6T4NW+ea1btWsMwFDFlLewekKYL4qdM+H17pFs0lbkfqk3lqWd3Bhr/0uCTcJLQd8pVdT8IMouBoZBYGl6NztYecpEsl9YeF5wB/seG8HMZQ1wvGXiGyI7RXdDNb32+qMBWErbvQkqSqy7rXgLl0zvxERkjIuyCbIviEHdZPPKbX3P06+Cqd+iIGmuGSNEVTcjYe97rKFNC8eCud1VcEkk+h/nkB3bJLwMD1zjfHRJpCKR3Eh6Oh5ulDgyE=

r_binary_packages:
  - abind
  - coda
  - codetools
  - DBI
  - foreign
  - ggplot2
  - inline
  - lattice
  - MASS
  - MCMCpack
  - mgcv
  - mvtnorm
  - nlme
  - Rcpp
  - rpart
  - stringr
  - survival

r_packages:
  - reticulate
  - tensorflow
  - R6
  - testthat
  - covr
  - DiagrammeR
  - knitr
  - rmarkdown
  - rsvg
  - bayesplot
  - extraDistr
  - devtools
  - tidyverse
  - lintr
  - colorspace
  - digest
  - XML
  - plyr

r_github_packages:
  - rich-iannone/DiagrammeRsvg

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      - libmagick++-dev
      - wget
      - libatlas3gf-base
      - libatlas-dev
      - python-joblib
      - python-dev
      - libv8-dev

before_install:
  - pip install --user numpy
  - pip install --user scipy
  - pip install --user 'tensorflow==1.14'
  - pip install --user 'tensorflow-probability==0.7.0'

after_success:
  - Rscript -e "covr::codecov()"
  - Rscript -e "lintr::lint_package()"

email:
  on_success: change
  on_failure: change
